// <auto-generated />
using System;
using DataAccess.EF.DbContextImplementation;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.EF.Migrations
{
    [DbContext(typeof(EfDbContext))]
    partial class EfDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DataAccess.Domain.Instance.WorkoutInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("StartedDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("WorkoutTemplateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutTemplateId");

                    b.ToTable("WorkoutInstances", (string)null);
                });

            modelBuilder.Entity("DataAccess.Domain.Instance.WorkoutInstanceMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ConfiguredMovementId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("WorkoutInstanceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConfiguredMovementId");

                    b.HasIndex("WorkoutInstanceId");

                    b.ToTable("WorkoutInstanceMovements", (string)null);
                });

            modelBuilder.Entity("DataAccess.Domain.Instance.WorkoutInstanceMovementSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Reps")
                        .HasColumnType("int");

                    b.Property<int>("SetNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("WorkoutInstanceMovementId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutInstanceMovementId");

                    b.ToTable("WorkoutInstanceMovementSets", (string)null);
                });

            modelBuilder.Entity("DataAccess.Domain.ReferenceData.ConfiguredMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("MovementConfigurationId")
                        .HasColumnType("int");

                    b.Property<int>("MovementId")
                        .HasColumnType("int");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<int?>("WorkoutTemplateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MovementConfigurationId");

                    b.HasIndex("MovementId");

                    b.HasIndex("WorkoutTemplateId");

                    b.ToTable("ConfiguredMovements", (string)null);
                });

            modelBuilder.Entity("DataAccess.Domain.ReferenceData.Movement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Movements", (string)null);
                });

            modelBuilder.Entity("DataAccess.Domain.ReferenceData.MovementConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("MovementId")
                        .HasColumnType("int");

                    b.Property<int>("RestTimeSeconds")
                        .HasColumnType("int");

                    b.Property<int>("SetRepRangeLowerBound")
                        .HasColumnType("int");

                    b.Property<int>("SetRepRangeUpperBound")
                        .HasColumnType("int");

                    b.Property<int>("TotalSets")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MovementId");

                    b.ToTable("MovementConfigurations", (string)null);
                });

            modelBuilder.Entity("DataAccess.Domain.ReferenceData.WorkoutTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("WorkoutTemplates", (string)null);
                });

            modelBuilder.Entity("DataAccess.Domain.Instance.WorkoutInstance", b =>
                {
                    b.HasOne("DataAccess.Domain.ReferenceData.WorkoutTemplate", "WorkoutTemplate")
                        .WithMany()
                        .HasForeignKey("WorkoutTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutTemplate");
                });

            modelBuilder.Entity("DataAccess.Domain.Instance.WorkoutInstanceMovement", b =>
                {
                    b.HasOne("DataAccess.Domain.ReferenceData.ConfiguredMovement", "ConfiguredMovement")
                        .WithMany()
                        .HasForeignKey("ConfiguredMovementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Domain.Instance.WorkoutInstance", null)
                        .WithMany("WorkoutInstanceMovements")
                        .HasForeignKey("WorkoutInstanceId");

                    b.Navigation("ConfiguredMovement");
                });

            modelBuilder.Entity("DataAccess.Domain.Instance.WorkoutInstanceMovementSet", b =>
                {
                    b.HasOne("DataAccess.Domain.Instance.WorkoutInstanceMovement", null)
                        .WithMany("Sets")
                        .HasForeignKey("WorkoutInstanceMovementId");
                });

            modelBuilder.Entity("DataAccess.Domain.ReferenceData.ConfiguredMovement", b =>
                {
                    b.HasOne("DataAccess.Domain.ReferenceData.MovementConfiguration", "MovementConfiguration")
                        .WithMany()
                        .HasForeignKey("MovementConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Domain.ReferenceData.Movement", "Movement")
                        .WithMany()
                        .HasForeignKey("MovementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Domain.ReferenceData.WorkoutTemplate", null)
                        .WithMany("ConfiguredMovements")
                        .HasForeignKey("WorkoutTemplateId");

                    b.Navigation("Movement");

                    b.Navigation("MovementConfiguration");
                });

            modelBuilder.Entity("DataAccess.Domain.ReferenceData.MovementConfiguration", b =>
                {
                    b.HasOne("DataAccess.Domain.ReferenceData.Movement", null)
                        .WithMany("MovementConfigurations")
                        .HasForeignKey("MovementId");
                });

            modelBuilder.Entity("DataAccess.Domain.Instance.WorkoutInstance", b =>
                {
                    b.Navigation("WorkoutInstanceMovements");
                });

            modelBuilder.Entity("DataAccess.Domain.Instance.WorkoutInstanceMovement", b =>
                {
                    b.Navigation("Sets");
                });

            modelBuilder.Entity("DataAccess.Domain.ReferenceData.Movement", b =>
                {
                    b.Navigation("MovementConfigurations");
                });

            modelBuilder.Entity("DataAccess.Domain.ReferenceData.WorkoutTemplate", b =>
                {
                    b.Navigation("ConfiguredMovements");
                });
#pragma warning restore 612, 618
        }
    }
}
